exclude: ['rp.photos.html', '*.md', 'CNAME', '.customPath', '*.code-workspace', 'Gemfile', 'Gemfile.lock', '.bundle/*.*', '.jekyll-cache/*.*', 'true']
gems:
  - jekyll-auto-image
  - jekyll-sitemap

nname: "Eireen"
aname: "Eireen Walsh"
aYears: "17"
aYdates: "29/11/2021"
nYears: "19"
lastForms: "https://docs.google.com/spreadsheets/d/e/2PACX-1vSGAxb8WDdQ1XN_mn4EFJzfjSvjqYxTons23l_cXEXXsIaDlDI3gK9x0zMPin7i8RR270JEAEUR6Kjk/pubhtml?gid=1163316673&single=true"